backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "assets/images/uploads" # Media files will be stored in the repo under assets/images/uploads

collections:
    - label: "Всі Сторінки"
      name: "pages"
      files:
          - label: "Головне Меню"
            name: "navbar"
            file: "_data/navigation.yml"
            fields:
                - label: Елемент Меню
                  name: navbar
                  widget: list
                  fields:
                      - {label: Назва, name: name, widget: string}
                      - {label: Лінк, name: link, widget: string}
         
          
       - label: Розклад
         name: timetable
         file: _data/table.yaml
         fields: 
            - label: "День"
              name: timetable
              fields:
              - label: "Місяць"
                name: march
                required: false
                widget: list
                fields: 
                   - 
                     label: День
                     name: day
                     required: false
                     widget: string
                   - 
                     label: Місяць
                     name: month
                     required: false
                     widget: string
                   - 
                     label: Час1
                     name: time1
                     required: false
                     widget: string
                   - 
                     label: Подія1
                     name: event1
                     required: false
                     widget: string
                   - 
                     label: Час2
                     name: time2
                     required: false
                     widget: string
                   - 
                     label: Подія2
                     name: event2
                     required: false
                     widget: string
                   - 
                     label: Час
                     name: time3
                     required: false
                     widget: string
                   - 
                     label: Подія3
                     name: event3
                     required: false
                     widget: string
                   - 
                     label: Захід
                     name: occasion
                     required: false
                     widget: string
                    

                    
