--- 
backend: 
  branch: master
  name: git-gateway
collections: 
  - 
    files: 
      - 
        fields: 
          - 
            fields: 
              - 
                label: День
                name: day
                widget: string
              - 
                label: Місяць
                name: month
                widget: string
              - 
                label: Час1
                name: time1
                widget: string
              - 
                label: Подія1
                name: event1
                widget: string
              - 
                label: Час2
                name: time2
                widget: string
              - 
                label: Подія2
                name: event2
                widget: string
              - 
                label: Час
                name: time3
                widget: string
              - 
                label: Подія3
                name: event3
                widget: string
              - 
                label: Захід
                name: occasion
                widget: string
            label: "Елемент Меню"
            name: timetable
            widget: list
        file: _data/table.yml
        label: Розклад
        name: timetable
    label: "Всі Сторінки"
    name: pages
media_folder: assets/images/uploads
publish_mode: editorial_workflow
